-- SOMAR VALORES DA TABELA CARRINHO (PRECO_TOTAL_PRODUTO) E JOGAR NA COLUMA TOTAL_CARRINHO DA TABELA PEDIDOS
CREATE
OR REPLACE FUNCTION CALCULAR_CARRINHO() RETURNS VOID AS $ $ BEGIN
UPDATE
    PEDIDOS AS P
SET
    TOTAL_CARRINHO = (
        SELECT
            SUM(C.PRECO_TOTAL_PRODUTO)
        FROM
            CARRINHO AS C
        WHERE
            C.PEDIDO = P.ID_PEDIDO
    );

END $ $ LANGUAGE PLPGSQL;