-- BASEADO NO TIPO_ENTREGA DA TABELA ENTREGA CALCULA O FRETE E ADICIONA O VALOR À COLUMA FRETE EM PEDIDOS (TABELA).
CREATE
OR REPLACE FUNCTION CALCULAR_FRETE() RETURNS VOID AS $$
BEGIN
UPDATE
    PEDIDOS AS P
SET
    FRETE = CASE
        E.TIPO_ENTREGA
        WHEN 'PADRÃO' THEN 0.00
        WHEN 'EXPRESSO' THEN 16.32
        WHEN 'PREMIUM' THEN 26.50
        ELSE 0.00
    END
FROM
    ENTREGA AS E
WHERE
    P.DESTINO = E.ID;

END;

$$ LANGUAGE PLPGSQL;