-- SOME OS VALORES DE FRETE E TOTAL_CARRINHO E SUBTRAIA DO VALOR_DESCONTO. JOGUE A SAÍDA DO COMANDO EM TOTAL_A_PAGAR NA TABELA PEDIDOS 
CREATE
OR REPLACE FUNCTION CALCULAR_TOTAL_A_PAGAR() RETURNS VOID AS 
$$ 
BEGIN
    UPDATE
        PEDIDOS
    SET
        TOTAL_A_PAGAR = (
            TOTAL_CARRINHO + FRETE - VALOR_DESCONTO
        );
END;
$$ LANGUAGE PLPGSQL;