-- CRIAR UMA TRIGGER QUE AO TROCAR O VALOR DE CONFIRMACAO_PAGAMENTO EM PEDIDOS PARA TRUE CRIE UMA NF E DEPOIS MANDE A LINHA CORRESPONDENTE EM PEDIDOS PARA A TABELA PEDIDOS_ARQUIVADOS 

-- FUNÇÃO QUE SERÁ CHAMADA PELO TRIGGER
CREATE OR REPLACE FUNCTION END_ORDER() RETURNS TRIGGER AS 
$$
DECLARE
    FLAG BOOLEAN
    BASEICMS REAL =: 28.0
    PERCENTUAL_ICMS REAL =: 0.12
BEGIN
    SELECT CONFIRMACAO_PAGAMENTO FROM PEDIDOS INTO FLAG;
    IF FLAG = TRUE THEN
        INSERT INTO NOTA_FISCAL(
            NOME_EMPRESA, ENTRADA_SAIDA, NUMERO_NF, CHAVE_ACESSO, NATUREZA_OPERACAO, PROTOCOLO, CNPJ, DATA_EMISSAO, 
            ADDRESS, NUMERO, ESTADO, UF, BAIRRO, CEP, TELEFONE, BASE_ICMS, VALOR_ICMS, VALOR_FRETE, DESCONTO, 
            TOTAL_TRIBUTOS, TOTAL_PRODUTOS, TOTAL_NF, ADDED_AT
        )
        VALUES (
            "DF PAPER COMPANY",
            1, 
            CONCAT('N°.', NEW.ID), 
            (SELECT STRING_AGG(TO_CHAR(FLOOR(RANDOM() * 10), '0000'), ' ') FROM GENERATE_SERIES(1, 11)), 
            'VENDA', 
            CONCAT(TO_CHAR(FLOOR(RANDOM() * 1000000000000000), '000000000000000'), ' ', TO_CHAR(NOW(), 'DD/MM/YYYY HH24:MI:SS')), 
            '00750343000173' --PODE VIR A MUDAR A MANEIRA COMO É PREENCHIDO, 
            NOW(), 
            (SELECT ADDRESS FROM ENTREGA AS E JOIN PEDIDOS AS P ON P.DESTINO = ENTREGA.ID), 
            (SELECT NUMERO FROM ENTREGA AS E JOIN PEDIDOS AS P ON P.DESTINO = ENTREGA.ID), 
            (SELECT ESTADO FROM ENTREGA AS E JOIN PEDIDOS AS P ON P.DESTINO = ENTREGA.ID), 
            (SELECT UF FROM ENTREGA AS E JOIN PEDIDOS AS P ON P.DESTINO = ENTREGA.ID), 
            (SELECT BAIRRO FROM ENTREGA AS E JOIN PEDIDOS AS P ON P.DESTINO = ENTREGA.ID), 
            (SELECT CEP FROM ENTREGA AS E JOIN PEDIDOS AS P ON P.DESTINO = ENTREGA.ID), 
            '35899337', 
            BASEICMS, 
            BASEICMS*PERCENTUAL_ICMS, 
            (SELECT FRETE FROM PRODUTOS AS P WHERE OLD.ID_PEDIDO = NEW.ID_PEDIDO), 
            (SELECT DESCONTO FROM PRODUTOS AS P WHERE OLD.ID_PEDIDO = NEW.ID_PEDIDO), 
            BASEICMS*PERCENTUAL_ICMS, 
            (SELECT TOTAL_A_PAGAR - (BASEICMS*PERCENTUAL_ICMS) - FRETE - DESCONTO FROM PEDIDOS), 
            (SELECT TOTAL_A_PAGAR FROM PEDIDOS), 
            NOW()
        )

        -- MOVER A LINHA CORRESPONDENTE DE PEDIDOS PARA PEDIDOS_ARQUIVADOS
        INSERT INTO PEDIDOS_ARQUIVADOS
        SELECT * FROM PEDIDOS WHERE ID = NEW.ID;

        -- DELETAR A LINHA DA TABELA PEDIDOS
        DELETE FROM PEDIDOS WHERE ID = NEW.ID;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE TRIGGER FECHAR_PEDIDO
AFTER UPDATE ON PEDIDOS
FOR EACH ROW
EXECUTE FUNCTION END_ORDER();
