-- IMPEDIR NOVAS INSERÇÕES EM ARMAZÉM QUANDO A QUANTIDADE DE LINHAS COM UM MESMO ID SERIAL FOR MAIOR QUE UM DADO NÚMERO CHAMADO CAPACIDADE TOTAL DO ARMAZÉM, DEVE-SE IMPEDIR NOVAS INSERÇÕES PARA AQUELE ID (ARMAZÉM) 

CREATE OR REPLACE FUNCTION CHECK_CAPACIDADE_ARMAZEM() RETURNS TRIGGER 
LANGUAGE PLPGSQL
AS $$
DECLARE
    QTD_ARMAZENADOS SMALLINT;
BEGIN
    SELECT COUNT(ID) INTO QTD_ARMAZENADOS
    FROM ARMAZEM
    WHERE ID = NEW.ID;

    
    IF QTD_ARMAZENADOS >= 300 THEN -- 300 FOI ARBITRÁRIO, PODE SER MUDADO DEPOIS
        RAISE EXCEPTION 'CAPACIDADE DO ARMAZÉM NÃO PODE SER EXCEDIDA. FALHA AO INSERIR NOVO ITEM!';
    END IF;
    
    RETURN NEW;
END;
$$;



CREATE TRIGGER MONITORAR_CAPACIDADE_ESTOQUE
BEFORE INSERT ON ARMAZEM
FOR EACH ROW
EXECUTE FUNCTION CHECK_CAPACIDADE_ARMAZEM();

