-- FUNÇÃO QUE SERÁ CHAMADA PELO TRIGGER
CREATE OR REPLACE FUNCTION LINK_UF_STATE() RETURNS TRIGGER 
LANGUAGE PLPGSQL
AS $$
BEGIN
    -- SUDESTE
    IF NEW.ESTADO = 'Rio de Janeiro' THEN
        NEW.UF := 'RJ';
    ELSIF NEW.ESTADO = 'São Paulo' THEN
        NEW.UF := 'SP';
    ELSIF NEW.ESTADO = 'Espírito Santo' THEN
        NEW.UF := 'ES';
    ELSIF NEW.ESTADO = 'Minas Gerais' THEN
        NEW.UF := 'MG';
    -- SUL
    ELSIF NEW.ESTADO = 'Paraná' THEN
        NEW.UF := 'PR';
    ELSIF NEW.ESTADO = 'Santa Catarina' THEN
        NEW.UF := 'SC';
    ELSIF NEW.ESTADO = 'Rio Grande do Sul' THEN
        NEW.UF := 'RS';
    -- CENTRO OESTE
    ELSIF NEW.ESTADO = 'Mato Grosso do Sul' THEN
        NEW.UF := 'MS';
    ELSIF NEW.ESTADO = 'Goiânia' THEN
        NEW.UF := 'GO';
    ELSIF NEW.ESTADO = 'Mato Grosso' THEN
        NEW.UF := 'MT';
    -- NORDESTE
    ELSIF NEW.ESTADO = 'Bahia' THEN
        NEW.UF := 'BA';
    ELSIF NEW.ESTADO = 'Sergipe' THEN
        NEW.UF := 'SE';
    ELSIF NEW.ESTADO = 'Alagoas' THEN
        NEW.UF := 'AL';
    ELSIF NEW.ESTADO = 'Pernambuco' THEN
        NEW.UF := 'PE';
    ELSIF NEW.ESTADO = 'Piauí' THEN
        NEW.UF := 'PI';
    ELSIF NEW.ESTADO = 'Maranhão' THEN
        NEW.UF := 'MA';
    ELSIF NEW.ESTADO = 'Paraíba' THEN
        NEW.UF := 'PB';
    ELSIF NEW.ESTADO = 'Rio Grande do Norte' THEN
        NEW.UF := 'RN';
    ELSIF NEW.ESTADO = 'Ceará' THEN
        NEW.UF := 'CE';
    -- NORTE
    ELSIF NEW.ESTADO = 'Rondônia' THEN
        NEW.UF := 'RO';
    ELSIF NEW.ESTADO = 'Amazonas' THEN
        NEW.UF := 'AM';
    ELSIF NEW.ESTADO = 'Tocantins' THEN
        NEW.UF := 'TO';
    ELSIF NEW.ESTADO = 'Pará' THEN
        NEW.UF := 'PA';
    ELSE
        RAISE EXCEPTION 'ESTADO INVÁLIDO';
    END IF;
    
    RETURN NEW;
END;
$$;

-- TRIGGER PARA A TABELA ENTREGA
CREATE OR REPLACE TRIGGER RESOLVE_UF_ENTREGA
BEFORE INSERT OR UPDATE ON ENTREGA
FOR EACH ROW
EXECUTE FUNCTION LINK_UF_STATE();

-- TRIGGER PARA A TABELA FORNECEDORES
CREATE OR REPLACE TRIGGER RESOLVE_UF_FORNECEDORES
BEFORE INSERT OR UPDATE ON FORNECEDORES
FOR EACH ROW
EXECUTE FUNCTION LINK_UF_STATE();

-- TRIGGER PARA A TABELA ARMAZEM
CREATE OR REPLACE TRIGGER RESOLVE_UF_ARMAZEM
BEFORE INSERT OR UPDATE ON ARMAZEM
FOR EACH ROW
EXECUTE FUNCTION LINK_UF_STATE();
