-- FAZER RESOLUÇÃO DE UF BASEADO NA CIDADE POR TRIGGER

CREATE OR REPLACE FUNCTION LINK_UF_STATE() RETURNS TRIGGER 
LANGUAGE PLPGSQL
AS $$
BEGIN
    -- SUDESTE
    IF NEW.ESTADO = 'RIO DE JANEIRO' THEN
        NEW.UF := 'RJ';
    ELSE IF NEW.ESTADO = 'SÃO PAULO' THEN
        NEW.UF := 'SP';
    ELSE IF NEW.ESTADO = 'ESPÍRITO SANTO' THEN
        NEW.UF := 'ES';
    ELSE IF NEW.ESTADO = 'MINAS GERAIS' THEN
        NEW.UF := 'MG';
    -- SUL
    ELSE IF NEW.ESTADO = 'PARANÁ' THEN
        NEW.UF := 'PR';
    ELSE IF NEW.ESTADO = 'SANTA CATARINA' THEN
        NEW.UF := 'SC';
    ELSE IF NEW.ESTADO = 'RIO GRANDE DO SUL' THEN
        NEW.UF := 'RS';
    -- CENTRO OESTE
    ELSE IF NEW.ESTADO = 'MATO GROSSO DO SUL' THEN
        NEW.UF := 'MS';
    ELSE IF NEW.ESTADO = 'GOIÂNIA' THEN
        NEW.UF := 'GO';
    ELSE IF NEW.ESTADO = 'MATO GROSSO' THEN
        NEW.UF := 'MT';
    -- NORDESTE
    ELSE IF NEW.ESTADO = 'BAHIA' THEN
        NEW.UF := 'BA';
    ELSE IF NEW.ESTADO = 'SERGIPE' THEN
        NEW.UF := 'SE';
    ELSE IF NEW.ESTADO = 'ALAGOAS' THEN
        NEW.UF := 'AL';
    ELSE IF NEW.ESTADO = 'PERNAMBUCO' THEN
        NEW.UF := 'PE';
    ELSE IF NEW.ESTADO = 'PIAUÍ' THEN
        NEW.UF := 'PI';
    ELSE IF NEW.ESTADO = 'MARANHÃO' THEN
        NEW.UF := 'MA';
    ELSE IF NEW.ESTADO = 'PARAÍBA' THEN
        NEW.UF := 'PB';
    ELSE IF NEW.ESTADO = 'RIO GRANDE DO NORTE' THEN
        NEW.UF := 'RN';
    ELSE IF NEW.ESTADO = 'CEARÁ' THEN
        NEW.UF := 'CE';
    -- NORTE
    ELSE IF NEW.ESTADO = 'RONDÔNIA' THEN
        NEW.UF := 'RO';
    ELSE IF NEW.ESTADO = 'AMAZONAS' THEN
        NEW.UF := 'AM';
    ELSE IF NEW.ESTADO = 'TOCANTINS' THEN
        NEW.UF := 'TO';
    ELSE IF NEW.ESTADO = 'PARÁ' THEN
        NEW.UF := 'PA';
    ELSE IF NEW.ESTADO = 'PARAÍBA' THEN
        NEW.UF := 'PB';
    ELSE
        RAISE EXCEPTION 'ESTADO INVÁLIDO';
    END IF;
    
    RETURN NEW;
END;
$$;


-- TRIGGER PARA A TABELA ENTREGA
CREATE TRIGGER RESOLVE_UF_ENTREGA
BEFORE INSERT OR UPDATE ON ENTREGA
FOR EACH ROW
EXECUTE FUNCTION LINK_UF_STATE();

-- TRIGGER PARA A TABELA FORNECEDORES
CREATE TRIGGER RESOLVE_UF_FORNECEDORES
BEFORE INSERT OR UPDATE ON FORNECEDORES
FOR EACH ROW
EXECUTE FUNCTION LINK_UF_STATE();

-- TRIGGER PARA A TABELA ARMAZEM
CREATE TRIGGER RESOLVE_UF_ARMAZEM
BEFORE INSERT OR UPDATE ON ARMAZEM
FOR EACH ROW
EXECUTE FUNCTION LINK_UF_STATE();
