-- FAZER UMA VIEW EM PEDIDOS QUE RETORNA O TOTAL GASTO PELO CLIENTE COM MAIS PEDIDOS FEITOS
CREATE VIEW gastos_cliente_n1 AS
SELECT
    ID_PEDIDO,
    SUM(TOTAL_A_PAGAR) AS TOTAL_GASTO
FROM
    PEDIDOS
WHERE
    CLIENTE = (
        SELECT
            CLIENTE
        FROM
            PEDIDOS
        GROUP BY
            CLIENTE
        ORDER BY
            COUNT(*) DESC
        LIMIT
            1
    )
GROUP BY
    CLIENTE, ID_PEDIDO;