-- CRIAR UMA VIEW QUE EXIBA PEDIDOS ARQUIVADOS COM DATA_PEDIDO DENTRO DO PRIMEIRO SEMESTRE DE 2023
CREATE VIEW PEDIDOS_ARQUIVADOS_23_1 AS
SELECT
    *
FROM
    PEDIDOS_ARQUIVADOS
WHERE
    DATE_PART('YEAR', DATA_PEDIDO) = 2023
    AND DATE_PART('MONTH', DATA_PEDIDO) <= 6;
