-- CRIAR UMA VIEW QUE EXIBA PEDIDOS ARQUIVADOS COM DATA_PEDIDO DENTRO DO PRIMEIRO SEMESTRE DE 2023
CREATE VIEW PEDIDOS_ARQUIVADOS_23_1 AS
SELECT
    *
FROM
    PEDIDOS
WHERE
    CONFIRMAR_PAGAMENTO = TRUE
    AND YEAR(DATA_PEDIDO) = 2023
    AND MONTH(DATA_PEDIDO) <= 6;