-- FAZER UMA VIEW QUE RETORNA OS 3 PRODUTOS EM MAIOR QUANTIDADE EM UM ARMAZÉM.
CREATE OR REPLACE VIEW TOP_3_ESTOQUE AS
SELECT
    ID,
	TIPO,
    QUANTIDADE_ESTOQUE
FROM
    PRODUTOS
WHERE LOCAL = 3	--SUBSTITUA AQUI PARA VERIFICAR DISPONIBILIDADE NOS DEMAIS ARMAZÉNS
ORDER BY
    QUANTIDADE_ESTOQUE DESC
LIMIT
    3;