-- FAZER UMA VIEW QUE RETORNA OS 3 PRODUTOS EM MAIOR QUANTIDADE NO ARMAZÉM.
CREATE VIEW TOP_3_ESTOQUE AS
SELECT
    PRODUTO_ID,
    TIPO_PRODUTO,
    QUANTIDADE_ESTOQUE
FROM
    ARMAZEM
ORDER BY
    QUANTIDADE_ESTOQUE DESC
LIMIT
    3;